# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #ADEAF3
background         #131416
cursor             #5EABB8

active_tab_foreground     #131416
active_tab_background     #ADEAF3
inactive_tab_foreground   #ADEAF3
inactive_tab_background   #131416

active_border_color   #ADEAF3
inactive_border_color #131416
bell_border_color     #0B3B46

color0      #3A3C3D
color1		#0B3B46
color2		#0C515E
color3		#0D6676
color4		#0E7C8E
color5		#0F92A7
color6		#0F92A7
color7		#81D8E6
color8		#5A97A1
color9		#0F4F5D
color10		#106C7D
color11		#11889D
color12		#13A5BE
color13		#14C2DE
color14		#14C2DE
color15		#81D8E6
